version: '3.8'

services:
  app:
    image: node:18
    container_name: auth-app
    command: tail -f /dev/null
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "8001:8001"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
