
export const MessageError = {
    //Auth
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    AUTHORIZATION_MIDDLEWARE: "AUTHORIZATION_MIDDLEWARE",
    PERMISSION_DENIED: "PERMISSION_DENIED",

    //User
    USERNAME_OR_EMAIL_EXISTED: "USERNAME_OR_EMAIL_EXISTED",
    USER_EXISTED_MIDDLEWARE: "USER_EXISTED_MIDDLEWARE",
    PASSWORD_FAIL: "PASSWORD_FAIL"
}